name: ShellCheck

on:
  push:
    branches: ["main"]
    paths:
      - "**.sh"
      - "scripts/**"
      - "pve-install.sh"
  pull_request:
    branches: ["main"]
    paths:
      - "**.sh"
      - "scripts/**"
      - "pve-install.sh"

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./scripts/src"
          severity: warning
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2034 -e SC2086

      - name: Run ShellCheck on main script
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: "pve-install.sh"
          severity: warning
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2034 -e SC2086
